import type * as Button from '#src/disreact/codec/rest-element/button.ts';
import type * as Embed from '#src/disreact/codec/rest-element/embed.ts';
import type * as Message from '#src/disreact/codec/rest-element/message.ts';
import type * as Markdown from '#src/disreact/codec/rest-element/markdown.ts';
import type * as Misc from '#src/disreact/codec/rest-element/misc.ts';
import type * as Modal from '#src/disreact/codec/rest-element/modal.ts';
import type * as Select from '#src/disreact/codec/rest-element/select.ts';

export interface IntrinsicAttributes {
  a         : Markdown.AnchorAttributes;
  at        : Markdown.AtMentionAttributes;
  b         : Markdown.BoldAttributes;
  blockquote: Markdown.BlockquoteAttributes;
  br        : Markdown.BreakAttributes;
  code      : Markdown.CodeAttributes;
  details   : Markdown.DetailsAttributes;
  h1        : Markdown.H1Attributes;
  h2        : Markdown.H2Attributes;
  h3        : Markdown.H3Attributes;
  i         : Markdown.ItalicAttributes;
  li        : Markdown.ListItemAttributes;
  mask      : Markdown.MaskAnchorAttributes;
  ol        : Markdown.OrderedListAttributes;
  pre       : Markdown.PreAttributes;
  s         : Markdown.StrikethroughAttributes;
  small     : Markdown.SmallAttributes;
  time      : Markdown.TimeAttributes;
  u         : Markdown.UnderlineAttributes;
  ul        : Markdown.UnorderedListAttributes;
  emoji     : Misc.EmojiAttributes;
  primary   : Button.PrimaryAttributes;
  secondary : Button.SecondaryAttributes;
  success   : Button.SuccessAttributes;
  danger    : Button.DangerAttributes;
  link      : Button.LinkAttributes;
  premium   : Button.PremiumAttributes;
  button    : Button.ButtonAttributes;
  actions   : Button.ActionsAttributes;
  author    : Embed.AuthorAttributes;
  embed     : Embed.EmbedAttributes;
  image     : Embed.ImageAttributes;
  field     : Embed.FieldAttributes;
  footer    : Embed.FooterAttributes;
  message   : Message.MessageAttributes;
  ephemeral : Message.EphemeralAttributes;
  modal     : Modal.ModalAttributes;
  textinput : Modal.TextInputAttributes;
  option    : Select.OptionAttributes;
  select    : Select.SelectAttributes;
  default   : Select.DefaultAttributes;
  channels  : Select.ChannelsAttributes;
  mentions  : Select.MentionsAttributes;
  roles     : Select.RolesAttributes;
  users     : Select.UsersAttributes;
}
