export const DFFP_CLANS_ALIAS = {
    dffp          : '#2GR2G0PGG',
    main          : '#2GR2G0PGG',
    labs          : '#2GYYRUULL',
    dffplabs      : '#2GYYRUULL',
    ct            : '#2YVCYUCCP',
    ctd           : '#2YVCYUCCP',
    ctdummy       : '#2YVCYUCCP',
    dummy         : '#2YVCYUCCP',
    clashtestdummy: '#2YVCYUCCP',
    ezcwl         : '#2QUP9UPGY',
    ace           : '#2P8UCYQQ0',
    acemini       : '#2R8L9QQG2',
    shit          : '#2RPLPCVLU',
    shithits      : '#2RPLPCVLU',
};
