const ENV = process.env.LAMBDA_ENV_UPPER;
const env = process.env.LAMBDA_ENV_LOWER;

export const REDACTED_DISCORD_BOT_TOKEN = `/DFFP/${ENV}/DISCORD_BOT_TOKEN`;
export const REDACTED_DISCORD_APP_ID = `/DFFP/${ENV}/DISCORD_APP_ID`;
export const REDACTED_DISCORD_ERROR_URL = `/DFFP/${ENV}/DISCORD_ERROR_URL`;
export const REDACTED_DISCORD_DEBUG_URL = `/DFFP/${ENV}/DISCORD_DEBUG_URL`;
export const REDACTED_DISCORD_PUBLIC_KEY = `/DFFP/${ENV}/DISCORD_PUBLIC_KEY`;
export const REDACTED_DISCORD_CLIENT_SECRET = `/DFFP/${ENV}/DISCORD_CLIENT_SECRET`;
export const REDACTED_DISCORD_CLIENT_ID = `/DFFP/${ENV}/DISCORD_CLIENT_ID`;
export const REDACTED_COC_KEY = `/DFFP/${ENV}/COC_KEY`;
export const REDACTED_COC_USER = `/DFFP/${ENV}/COC_USER`;
export const REDACTED_COC_PASSWORD = `/DFFP/${ENV}/COC_PASSWORD`;
export const REDACTED_DEVIDS = `/dffp/${env}/devids`;
