export const tag = {
  // Document structure
  html: {
    lang: 'string',
    dir : 'string',
  },
  head: {},
  body: {
    onload  : 'string',
    onunload: 'string',
  },

  // Metadata
  title: {},
  meta : {
    charset     : 'string',
    content     : 'string',
    name        : 'string',
    'http-equiv': 'string',
    viewport    : 'string',
  },
  link: {
    rel        : 'string',
    href       : 'string',
    type       : 'string',
    media      : 'string',
    sizes      : 'string',
    crossorigin: 'string',
  },
  base: {
    href  : 'string',
    target: 'string',
  },
  style: {
    type : 'string',
    media: 'string',
  },
  script: {
    src        : 'string',
    type       : 'string',
    async      : 'boolean',
    defer      : 'boolean',
    crossorigin: 'string',
    integrity  : 'string',
  },

  // Sectioning
  main   : {},
  header : {},
  footer : {},
  nav    : {},
  aside  : {},
  section: {},
  article: {},
  h1     : {},
  h2     : {},
  h3     : {},
  h4     : {},
  h5     : {},
  h6     : {},
  hgroup : {},

  // Content grouping
  div       : {},
  p         : {},
  blockquote: {cite: 'string'},
  pre       : {},
  hr        : {},
  dl        : {},
  dt        : {},
  dd        : {},
  figure    : {},
  figcaption: {},
  li        : {value: 'number'},
  ul        : {},
  ol        : {
    reversed: 'boolean',
    start   : 'number',
    type    : 'string',
  },

  // Text-level semantics
  a: {
    href    : 'string',
    target  : 'string',
    download: 'string',
    rel     : 'string',
    type    : 'string',
    hreflang: 'string',
  },
  em    : {},
  strong: {},
  small : {},
  s     : {},
  cite  : {},
  q     : {cite: 'string'},
  dfn   : {},
  abbr  : {title: 'string'},
  ruby  : {},
  rt    : {},
  rp    : {},
  data  : {value: 'string'},
  time  : {datetime: 'string'},
  code  : {},
  var   : {},
  samp  : {},
  kbd   : {},
  sub   : {},
  sup   : {},
  i     : {},
  b     : {},
  u     : {},
  mark  : {},
  bdi   : {dir: 'string'},
  bdo   : {dir: 'string'},
  span  : {},
  br    : {},
  wbr   : {},

  // Embedded content
  picture: {},
  source : {
    src   : 'string',
    srcset: 'string',
    media : 'string',
    sizes : 'string',
    type  : 'string',
  },
  img: {
    src        : 'string',
    alt        : 'string',
    width      : 'number',
    height     : 'number',
    srcset     : 'string',
    sizes      : 'string',
    crossorigin: 'string',
    usemap     : 'string',
    loading    : 'string',
    decoding   : 'string',
  },
  iframe: {
    src            : 'string',
    srcdoc         : 'string',
    name           : 'string',
    sandbox        : 'string',
    allow          : 'string',
    allowfullscreen: 'boolean',
    width          : 'number',
    height         : 'number',
    loading        : 'string',
  },
  embed: {
    src   : 'string',
    type  : 'string',
    width : 'number',
    height: 'number',
  },
  object: {
    data  : 'string',
    type  : 'string',
    name  : 'string',
    usemap: 'string',
    form  : 'string',
    width : 'number',
    height: 'number',
  },
  video: {
    src        : 'string',
    crossorigin: 'string',
    poster     : 'string',
    preload    : 'string',
    autoplay   : 'boolean',
    playsinline: 'boolean',
    loop       : 'boolean',
    muted      : 'boolean',
    controls   : 'boolean',
    width      : 'number',
    height     : 'number',
  },
  audio: {
    src        : 'string',
    crossorigin: 'string',
    preload    : 'string',
    autoplay   : 'boolean',
    loop       : 'boolean',
    muted      : 'boolean',
    controls   : 'boolean',
  },
  track: {
    default: 'boolean',
    kind   : 'string',
    label  : 'string',
    src    : 'string',
    srclang: 'string',
  },
  map : {name: 'string'},
  area: {
    alt     : 'string',
    coords  : 'string',
    shape   : 'string',
    href    : 'string',
    target  : 'string',
    download: 'string',
    rel     : 'string',
  },

  // Tabular data
  table   : {},
  caption : {},
  colgroup: {span: 'number'},
  col     : {span: 'number'},
  tbody   : {},
  thead   : {},
  tfoot   : {},
  tr      : {},
  td      : {
    colspan: 'number',
    rowspan: 'number',
    headers: 'string',
  },
  th: {
    colspan: 'number',
    rowspan: 'number',
    headers: 'string',
    scope  : 'string',
    abbr   : 'string',
  },

  // Forms
  form: {
    'accept-charset': 'string',
    action          : 'string',
    autocomplete    : 'string',
    enctype         : 'string',
    method          : 'string',
    name            : 'string',
    novalidate      : 'boolean',
    target          : 'string',
  },
  label: {for: 'string'},
  input: {
    accept        : 'string',
    alt           : 'string',
    autocomplete  : 'string',
    checked       : 'boolean',
    dirname       : 'string',
    disabled      : 'boolean',
    form          : 'string',
    formaction    : 'string',
    formenctype   : 'string',
    formmethod    : 'string',
    formnovalidate: 'boolean',
    formtarget    : 'string',
    height        : 'number',
    list          : 'string',
    max           : 'string',
    maxlength     : 'number',
    min           : 'string',
    minlength     : 'number',
    multiple      : 'boolean',
    name          : 'string',
    pattern       : 'string',
    placeholder   : 'string',
    readonly      : 'boolean',
    required      : 'boolean',
    size          : 'number',
    src           : 'string',
    step          : 'string',
    type          : 'string',
    value         : 'string',
    width         : 'number',
  },
  button: {
    disabled      : 'boolean',
    form          : 'string',
    formaction    : 'string',
    formenctype   : 'string',
    formmethod    : 'string',
    formnovalidate: 'boolean',
    formtarget    : 'string',
    name          : 'string',
    type          : 'string',
    value         : 'string',
  },
  select: {
    autocomplete: 'string',
    disabled    : 'boolean',
    form        : 'string',
    multiple    : 'boolean',
    name        : 'string',
    required    : 'boolean',
    size        : 'number',
  },
  datalist: {},
  optgroup: {
    disabled: 'boolean',
    label   : 'string',
  },
  option: {
    disabled: 'boolean',
    label   : 'string',
    selected: 'boolean',
    value   : 'string',
  },
  textarea: {
    autocomplete: 'string',
    cols        : 'number',
    dirname     : 'string',
    disabled    : 'boolean',
    form        : 'string',
    maxlength   : 'number',
    minlength   : 'number',
    name        : 'string',
    placeholder : 'string',
    readonly    : 'boolean',
    required    : 'boolean',
    rows        : 'number',
    wrap        : 'string',
  },
  output: {
    for : 'string',
    form: 'string',
    name: 'string',
  },
  progress: {
    value: 'number',
    max  : 'number',
  },
  meter: {
    value  : 'number',
    min    : 'number',
    max    : 'number',
    low    : 'number',
    high   : 'number',
    optimum: 'number',
  },
  fieldset: {
    disabled: 'boolean',
    form    : 'string',
    name    : 'string',
  },
  legend: {},

  // Interactive elements
  details: {open: 'boolean'},
  summary: {},
  dialog : {open: 'boolean'},

  // Scripting
  canvas: {
    width : 'number',
    height: 'number',
  },
  noscript: {},
  template: {},
  slot    : {name: 'string'},

  // Web Components / Custom Elements
  search: {},
  menu  : {},
} as const;

// Global attributes that apply to all elements
export const any = {
  // Core attributes
  id   : 'string',
  class: 'string',
  style: 'string',
  title: 'string',

  // Language attributes
  lang: 'string',
  dir : 'string',

  // Accessibility attributes
  role              : 'string',
  'aria-label'      : 'string',
  'aria-labelledby' : 'string',
  'aria-describedby': 'string',
  'aria-hidden'     : 'boolean',
  'aria-expanded'   : 'boolean',
  'aria-selected'   : 'boolean',
  'aria-checked'    : 'boolean',
  'aria-disabled'   : 'boolean',
  'aria-readonly'   : 'boolean',
  'aria-required'   : 'boolean',
  'aria-invalid'    : 'boolean',
  'aria-live'       : 'string',
  'aria-atomic'     : 'boolean',
  'aria-relevant'   : 'string',

  // Data attributes (pattern)
  'data-*': 'string',

  // Event handlers (common ones)
  onclick    : 'string',
  onchange   : 'string',
  onsubmit   : 'string',
  onload     : 'string',
  onerror    : 'string',
  onfocus    : 'string',
  onblur     : 'string',
  onmouseover: 'string',
  onmouseout : 'string',
  onkeydown  : 'string',
  onkeyup    : 'string',

  // Other global attributes
  contenteditable: 'boolean',
  draggable      : 'boolean',
  hidden         : 'boolean',
  spellcheck     : 'boolean',
  tabindex       : 'number',
  translate      : 'string',
  autocapitalize : 'string',
  inputmode      : 'string',
  is             : 'string',
  itemid         : 'string',
  itemprop       : 'string',
  itemref        : 'string',
  itemscope      : 'boolean',
  itemtype       : 'string',
  slot           : 'string',
} as const;
