export {
    appendAll as concatL,
    filter as filterL,
    flatMap as flatMapL,
    flatten as flattenL,
    map as mapL,
    reduce as reduceL,
    sort as sortL,
    zip as zipL,
    of as ofL,
    dedupe as dedupeL,
    contains as containsL,
    partition as partitionL,
    head as headL,
    tail as tailL,
} from 'effect/Array';
