import * as All from './all.ts';

export const at         = All.at;
export const a          = All.a;
export const mask       = All.mask;
export const p          = All.p;
export const br         = All.br;
export const b          = All.b;
export const i          = All.i;
export const u          = All.u;
export const s          = All.s;
export const details    = All.details;
export const code       = All.code;
export const pre        = All.pre;
export const blockquote = All.blockquote;
export const h1         = All.h1;
export const h2         = All.h2;
export const h3         = All.h3;
export const small      = All.small;
export const ol         = All.ol;
export const ul         = All.ul;
export const li         = All.li;
