import * as Button from '#src/disreact/codec/intrinsic/button.ts';
import * as Embed from '#src/disreact/codec/intrinsic/embed.ts';
import * as Markdown from '#src/disreact/codec/intrinsic/markdown.ts';
import * as Message from '#src/disreact/codec/intrinsic/message.ts';
import * as Misc from '#src/disreact/codec/intrinsic/misc.ts';
import * as Modal from '#src/disreact/codec/intrinsic/modal.ts';
import * as Select from '#src/disreact/codec/intrinsic/select.ts';
import * as Norm from '#src/disreact/codec/intrinsic/norm.ts';

export const primitive = Norm.PRIMITIVE;

export const normalization = {
  [Markdown.ANCHOR]        : Norm.PRIMITIVE,
  [Markdown.AT_MENTION]    : Norm.PRIMITIVE,
  [Markdown.BOLD]          : Norm.PRIMITIVE,
  [Markdown.BLOCKQUOTE]    : Norm.PRIMITIVE,
  [Markdown.BREAK]         : Norm.PRIMITIVE,
  [Markdown.CODE]          : Norm.PRIMITIVE,
  [Markdown.DETAILS]       : Norm.PRIMITIVE,
  [Markdown.H1]            : Norm.PRIMITIVE,
  [Markdown.H2]            : Norm.PRIMITIVE,
  [Markdown.H3]            : Norm.PRIMITIVE,
  [Markdown.ITALIC]        : Norm.PRIMITIVE,
  [Markdown.LIST_ITEM]     : Norm.PRIMITIVE,
  [Markdown.MASK_ANCHOR]   : Norm.PRIMITIVE,
  [Markdown.ORDERED_LIST]  : Norm.PRIMITIVE,
  [Markdown.PARAGRAPH]     : Norm.PRIMITIVE,
  [Markdown.PRE]           : Norm.PRIMITIVE,
  [Markdown.STRIKETHROUGH] : Norm.PRIMITIVE,
  [Markdown.SMALL]         : Norm.PRIMITIVE,
  [Markdown.TIME]          : Norm.PRIMITIVE,
  [Markdown.UNDERLINE]     : Norm.PRIMITIVE,
  [Markdown.UNORDERED_LIST]: Norm.PRIMITIVE,
  [Misc.EMOJI]             : Misc.EMOJI,
  [Button.PRIMARY]         : Norm.BUTTONS,
  [Button.SECONDARY]       : Norm.BUTTONS,
  [Button.SUCCESS]         : Norm.BUTTONS,
  [Button.DANGER]          : Norm.BUTTONS,
  [Button.LINK]            : Norm.BUTTONS,
  [Button.PREMIUM]         : Norm.BUTTONS,
  [Button.BUTTON]          : Norm.BUTTONS,
  [Button.ACTIONS]         : Norm.COMPONENTS,
  [Embed.AUTHOR]           : Embed.AUTHOR,
  [Embed.FIELD]            : Embed.FIELD,
  [Embed.IMAGE]            : Embed.IMAGE,
  [Embed.FOOTER]           : Embed.FOOTER,
  [Embed.EMBED]            : Embed.EMBED,
  [Message.MESSAGE]        : Message.MESSAGE,
  [Message.EPHEMERAL]      : Message.EPHEMERAL,
  [Modal.TEXT_INPUT]       : Norm.COMPONENTS,
  [Modal.MODAL]            : Modal.MODAL,
  [Select.OPTION]          : Select.OPTION,
  [Select.DEFAULT]         : Select.DEFAULT,
  [Select.SELECT]          : Norm.COMPONENTS,
  [Select.CHANNELS]        : Norm.COMPONENTS,
  [Select.MENTIONS]        : Norm.COMPONENTS,
  [Select.ROLES]           : Norm.COMPONENTS,
  [Select.USERS]           : Norm.COMPONENTS,
};

export const encoding = {
  [Markdown.ANCHOR]        : Markdown.encodeAnchor,
  [Markdown.AT_MENTION]    : Markdown.encodeAtMention,
  [Markdown.BOLD]          : Markdown.encodeBold,
  [Markdown.BLOCKQUOTE]    : Markdown.encodeBlockquote,
  [Markdown.BREAK]         : Markdown.encodeBreak,
  [Markdown.CODE]          : Markdown.encodeCode,
  [Markdown.DETAILS]       : Markdown.encodeDetails,
  [Markdown.H1]            : Markdown.encodeH1,
  [Markdown.H2]            : Markdown.encodeH2,
  [Markdown.H3]            : Markdown.encodeH3,
  [Markdown.ITALIC]        : Markdown.encodeItalic,
  [Markdown.LIST_ITEM]     : Markdown.encodeListItem,
  [Markdown.MASK_ANCHOR]   : Markdown.encodeMaskAnchor,
  [Markdown.ORDERED_LIST]  : Markdown.encodeOrderedList,
  [Markdown.PARAGRAPH]     : Markdown.encodeParagraph,
  [Markdown.PRE]           : Markdown.encodePre,
  [Markdown.STRIKETHROUGH] : Markdown.encodeStrikethrough,
  [Markdown.SMALL]         : Markdown.encodeSmall,
  [Markdown.TIME]          : Markdown.encodeTime,
  [Markdown.UNDERLINE]     : Markdown.encodeUnderline,
  [Markdown.UNORDERED_LIST]: Markdown.encodeUnorderedList,
  [Misc.EMOJI]             : Misc.encodeEmoji,
  [Button.PRIMARY]         : Button.encodePrimary,
  [Button.SECONDARY]       : Button.encodeSecondary,
  [Button.SUCCESS]         : Button.encodeSuccess,
  [Button.DANGER]          : Button.encodeDanger,
  [Button.LINK]            : Button.encodeLink,
  [Button.PREMIUM]         : Button.encodePremium,
  [Button.BUTTON]          : Button.encodeButton,
  [Button.ACTIONS]         : Button.encodeActions,
  [Embed.AUTHOR]           : Embed.encodeAuthor,
  [Embed.FIELD]            : Embed.encodeField,
  [Embed.IMAGE]            : Embed.encodeImage,
  [Embed.FOOTER]           : Embed.encodeFooter,
  [Embed.EMBED]            : Embed.encodeEmbed,
  [Message.MESSAGE]        : Message.encodeMessage,
  [Message.EPHEMERAL]      : Message.encodeEphemeral,
  [Modal.TEXT_INPUT]       : Modal.encodeTextInput,
  [Modal.MODAL]            : Modal.encodeModal,
  [Select.OPTION]          : Select.encodeOption,
  [Select.SELECT]          : Select.encodeSelect,
  [Select.DEFAULT]         : Select.encodeDefault,
  [Select.CHANNELS]        : Select.encodeChannels,
  [Select.MENTIONS]        : Select.encodeMentions,
  [Select.ROLES]           : Select.encodeRoles,
  [Select.USERS]           : Select.encodeUsers,
};
