import {S} from '#src/internal/pure/effect.ts';
import {decodeUnknownSync} from 'effect/Schema';

export const playerWarhits = S.Struct ({
  war_data: S.Struct({
    state               : S.String,
    teamSize            : S.Int,
    attacksPerMember    : S.Int,
    battleModifier      : S.String,
    preparationStartTime: S.DateTimeUtc,
    startTime           : S.DateTimeUtc,
    endTime             : S.DateTimeUtc,
    clan                : S.Struct({
        tag      : S.String,
        name     : S.String,
        badgeUrls: S.Struct({
            small : S.String,
            large : S.String,
            medium: S.String,
        }),
      clanLevel            : S.Int,
      attacks              : S.Int,
      stars                : S.Int,
      destructionPercentage: S.Int,
    }),
    opponent: S.Struct({
      tag      : S.String,
      name     : S.String,
      badgeUrls: S.Struct({
        small : S.String,
        large : S.String,
        medium: S.String,
      }),
      clanLevel            : S.Int,
      attacks              : S.Int,
      stars                : S.Int,
      destructionPercentage: S.Int,
    }),
    type: S.String,
  }),
  memberData: S.Struct({
    tag            : S.String,
    name           : S.String,
    townhallLevel  : S.Int,
    mapPosition    : S.Int,
    opponentAttacks: S.Int,
  }),
  attacks: S.Array(
    S.Struct({
    attackerTag          : S.String,
    defenderTag          : S.String,
    stars                : S.Int,
    destructionPercentage: S.Int,
    order                : S.Int,
    duration             : S.Int,
    fresh                : S.Boolean,
    defender             : S.Struct({
      tag            : S.String,
      name           : S.String,
      townhallLevel  : S.Int,
      mapPosition    : S.Int,
      opponentAttacks: S.Int,
    }),
    attack_order: S.Int,
  }),
  ),
  defenses: S.Array(
    S.Struct({
      attackerTag          : S.String,
      defenderTag          : S.String,
      stars                : S.Int,
      destructionPercentage: S.Int,
      order                : S.Int,
      duration             : S.Int,
      fresh                : S.Boolean,
      defender             : S.Struct({
        tag            : S.String,
        name           : S.String,
        townhallLevel  : S.Int,
        mapPosition    : S.Int,
        opponentAttacks: S.Int,
      }),
      attack_order: S.Int,
    }),
  ),
});

const decoder = decodeUnknownSync(playerWarhits);
console.log(decoder({
  war_data: {
  state               : 'warEnded',
    teamSize            : 35,
    attacksPerMember    : 2,
    battleModifier      : 'none',
    preparationStartTime: '20250429T092646.000Z',
    startTime           : '20250430T082646.000Z',
    endTime             : '20250501T082646.000Z',
    clan                : {
    tag      : '#2GR2G0PGG',
      name     : 'DFFP',
      badgeUrls: {
      small : 'https://api-assets.clashofclans.com/badges/70/pE_V18dUS3FdyCFhaGOHLAyyy4FWGEYeYKnEX9GqvJY.png',
        large : 'https://api-assets.clashofclans.com/badges/512/pE_V18dUS3FdyCFhaGOHLAyyy4FWGEYeYKnEX9GqvJY.png',
        medium: 'https://api-assets.clashofclans.com/badges/200/pE_V18dUS3FdyCFhaGOHLAyyy4FWGEYeYKnEX9GqvJY.png',
    },
    clanLevel            : 17,
      attacks              : 49,
      stars                : 91,
      destructionPercentage: 87.8,
  },
  opponent: {
    tag      : '#8ULYPY20',
      name     : '地球村',
      badgeUrls: {
      small : 'https://api-assets.clashofclans.com/badges/70/7TKwuNqwjHJqXG_9_GBSWBEwHaUb1hVXu6Mas-v30Vo.png',
        large : 'https://api-assets.clashofclans.com/badges/512/7TKwuNqwjHJqXG_9_GBSWBEwHaUb1hVXu6Mas-v30Vo.png',
        medium: 'https://api-assets.clashofclans.com/badges/200/7TKwuNqwjHJqXG_9_GBSWBEwHaUb1hVXu6Mas-v30Vo.png',
    },
    clanLevel            : 16,
      attacks              : 66,
      stars                : 105,
      destructionPercentage: 100,
  },
  type: 'random',
},
  member_data: {
  tag            : '#Y82Q9Q98',
    name           : 'Kronith',
    townhallLevel  : 17,
    mapPosition    : 4,
    opponentAttacks: 2,
},
  attacks: [
  {
    attackerTag          : '#Y82Q9Q98',
    defenderTag          : '#90QVYGCVC',
    stars                : 3,
    destructionPercentage: 100,
    order                : 64,
    duration             : 142,
    fresh                : false,
    defender             : {
      tag            : '#90QVYGCVC',
      name           : 'the',
      townhallLevel  : 17,
      mapPosition    : 1,
      opponentAttacks: 3,
    },
    attack_order: 64,
  },
  {
    attackerTag          : '#Y82Q9Q98',
    defenderTag          : '#QRCRRPQ82',
    stars                : 3,
    destructionPercentage: 100,
    order                : 66,
    duration             : 136,
    fresh                : false,
    defender             : {
      tag            : '#QRCRRPQ82',
      name           : '7号线',
      townhallLevel  : 17,
      mapPosition    : 2,
      opponentAttacks: 2,
    },
    attack_order: 66,
  },
],
  defenses: [
  {
    attackerTag          : '#GP02V9YCG',
    defenderTag          : '#Y82Q9Q98',
    stars                : 1,
    destructionPercentage: 25,
    order                : 86,
    duration             : 32,
    fresh                : false,
    attacker             : {
      tag            : '#GP02V9YCG',
      name           : '小宇',
      townhallLevel  : 16,
      mapPosition    : 22,
      opponentAttacks: 1,
    },
    attack_order: 86,
  },
  {
    attackerTag          : '#QCYY8PJRV',
    defenderTag          : '#Y82Q9Q98',
    stars                : 3,
    destructionPercentage: 100,
    order                : 4,
    duration             : 76,
    fresh                : true,
    attacker             : {
      tag            : '#QCYY8PJRV',
      name           : '阿虾',
      townhallLevel  : 17,
      mapPosition    : 3,
      opponentAttacks: 2,
    },
    attack_order: 4,
  },
],
}));
