import type * as Button from '#src/disreact/codec/rest-element/button.ts';
import type * as Embed from '#src/disreact/codec/rest-element/embed.ts';
import type * as Message from '#src/disreact/codec/rest-element/message.ts';
import type * as Markdown from '#src/disreact/codec/rest-element/markdown.ts';
import type * as Misc from '#src/disreact/codec/rest-element/misc.ts';
import type * as Modal from '#src/disreact/codec/rest-element/modal.ts';
import type * as Select from '#src/disreact/codec/rest-element/select.ts';

export interface IntrinsicAttributesMap {
  a         : Markdown.AnchorAttributes & {children?: any};
  at        : Markdown.AtMentionAttributes & {children?: any};
  b         : Markdown.BoldAttributes & {children?: any};
  blockquote: Markdown.BlockquoteAttributes & {children?: any};
  br        : Markdown.BreakAttributes & {children?: any};
  code      : Markdown.CodeAttributes & {children?: any};
  details   : Markdown.DetailsAttributes & {children?: any};
  h1        : Markdown.H1Attributes & {children?: any};
  h2        : Markdown.H2Attributes & {children?: any};
  h3        : Markdown.H3Attributes & {children?: any};
  i         : Markdown.ItalicAttributes & {children?: any};
  li        : Markdown.ListItemAttributes & {children?: any};
  mask      : Markdown.MaskAnchorAttributes & {children?: any};
  ol        : Markdown.OrderedListAttributes & {children?: any};
  pre       : Markdown.PreAttributes & {children?: any};
  s         : Markdown.StrikethroughAttributes & {children?: any};
  small     : Markdown.SmallAttributes & {children?: any};
  time      : Markdown.TimeAttributes & {children?: any};
  u         : Markdown.UnderlineAttributes & {children?: any};
  ul        : Markdown.UnorderedListAttributes & {children?: any};
  emoji     : Misc.EmojiAttributes & {children?: any};
  primary   : Button.PrimaryAttributes & {children?: any};
  secondary : Button.SecondaryAttributes & {children?: any};
  success   : Button.SuccessAttributes & {children?: any};
  danger    : Button.DangerAttributes & {children?: any};
  link      : Button.LinkAttributes & {children?: any};
  premium   : Button.PremiumAttributes & {children?: any};
  button    : Button.ButtonAttributes & {children?: any};
  actions   : Button.ActionsAttributes & {children?: any};
  author    : Embed.AuthorAttributes & {children?: any};
  embed     : Embed.EmbedAttributes & {children?: any};
  image     : Embed.ImageAttributes & {children?: any};
  field     : Embed.FieldAttributes & {children?: any};
  footer    : Embed.FooterAttributes & {children?: any};
  message   : Message.MessageAttributes & {children?: any};
  ephemeral : Message.EphemeralAttributes & {children?: any};
  modal     : Modal.ModalAttributes & {children?: any};
  textinput : Modal.TextInputAttributes & {children?: any};
  option    : Select.OptionAttributes & {children?: any};
  select    : Select.SelectAttributes & {children?: any};
  default   : Select.DefaultAttributes & {children?: any};
  channels  : Select.ChannelsAttributes & {children?: any};
  mentions  : Select.MentionsAttributes & {children?: any};
  roles     : Select.RolesAttributes & {children?: any};
  users     : Select.UsersAttributes & {children?: any};
}
