import * as Button from '#disreact/rest/schema/intrinsic/button.ts';
import * as Container from '#disreact/rest/schema/intrinsic/container.ts';
import * as Embed from '#disreact/rest/schema/intrinsic/embed.ts';
import * as Markdown from '#disreact/rest/schema/intrinsic/markdown.ts';
import * as Norm from '#disreact/rest/schema/intrinsic/norm.ts';
import * as Select from '#disreact/rest/schema/intrinsic/select.ts';

export const primitive = Norm.PRIMITIVE;

export const normalization = {
  [Markdown.ANCHOR]        : primitive,
  [Markdown.AT_MENTION]    : primitive,
  [Markdown.BOLD]          : primitive,
  [Markdown.BLOCKQUOTE]    : primitive,
  [Markdown.BREAK]         : primitive,
  [Markdown.CODE]          : primitive,
  [Markdown.DETAILS]       : primitive,
  [Markdown.H1]            : primitive,
  [Markdown.H2]            : primitive,
  [Markdown.H3]            : primitive,
  [Markdown.ITALIC]        : primitive,
  [Markdown.LIST_ITEM]     : primitive,
  [Markdown.MASK_ANCHOR]   : primitive,
  [Markdown.ORDERED_LIST]  : primitive,
  [Markdown.PARAGRAPH]     : primitive,
  [Markdown.PRE]           : primitive,
  [Markdown.STRIKETHROUGH] : primitive,
  [Markdown.SMALL]         : primitive,
  [Markdown.TIME]          : primitive,
  [Markdown.UNDERLINE]     : primitive,
  [Markdown.UNORDERED_LIST]: primitive,
  [Markdown.EMOJI]         : Markdown.EMOJI,
  [Button.PRIMARY]         : Norm.COMPONENTS,
  [Button.SECONDARY]       : Norm.COMPONENTS,
  [Button.SUCCESS]         : Norm.COMPONENTS,
  [Button.DANGER]          : Norm.COMPONENTS,
  [Button.LINK]            : Norm.COMPONENTS,
  [Button.PREMIUM]         : Norm.COMPONENTS,
  [Button.BUTTON]          : Norm.COMPONENTS,
  [Button.ACTIONS]         : Norm.COMPONENTS,
  [Embed.AUTHOR]           : Embed.AUTHOR,
  [Embed.FIELD]            : Embed.FIELD,
  [Embed.IMAGE]            : Embed.IMAGE,
  [Embed.FOOTER]           : Embed.FOOTER,
  [Embed.EMBED]            : Embed.EMBED,
  [Container.MESSAGE]      : Container.MESSAGE,
  [Container.EPHEMERAL]    : Container.MESSAGE,
  [Container.TEXT_INPUT]   : Norm.COMPONENTS,
  [Container.MODAL]        : Container.MODAL,
  [Select.OPTION]          : Select.OPTION,
  [Select.DEFAULT]         : Select.DEFAULT,
  [Select.SELECT]          : Norm.COMPONENTS,
  [Select.CHANNELS]        : Norm.COMPONENTS,
  [Select.MENTIONS]        : Norm.COMPONENTS,
  [Select.ROLES]           : Norm.COMPONENTS,
  [Select.USERS]           : Norm.COMPONENTS,
};

export const encoding = {
  [Markdown.ANCHOR]        : Markdown.encodeAnchor,
  [Markdown.AT_MENTION]    : Markdown.encodeAtMention,
  [Markdown.BOLD]          : Markdown.encodeBold,
  [Markdown.BLOCKQUOTE]    : Markdown.encodeBlockquote,
  [Markdown.BREAK]         : Markdown.encodeBreak,
  [Markdown.CODE]          : Markdown.encodeCode,
  [Markdown.DETAILS]       : Markdown.encodeDetails,
  [Markdown.H1]            : Markdown.encodeH1,
  [Markdown.H2]            : Markdown.encodeH2,
  [Markdown.H3]            : Markdown.encodeH3,
  [Markdown.ITALIC]        : Markdown.encodeItalic,
  [Markdown.LIST_ITEM]     : Markdown.encodeListItem,
  [Markdown.MASK_ANCHOR]   : Markdown.encodeMaskAnchor,
  [Markdown.ORDERED_LIST]  : Markdown.encodeOrderedList,
  [Markdown.PARAGRAPH]     : Markdown.encodeParagraph,
  [Markdown.PRE]           : Markdown.encodePre,
  [Markdown.STRIKETHROUGH] : Markdown.encodeStrikethrough,
  [Markdown.SMALL]         : Markdown.encodeSmall,
  [Markdown.TIME]          : Markdown.encodeTime,
  [Markdown.UNDERLINE]     : Markdown.encodeUnderline,
  [Markdown.UNORDERED_LIST]: Markdown.encodeUnorderedList,
  [Markdown.EMOJI]         : Markdown.encodeEmoji,
  [Button.PRIMARY]         : Button.encodePrimary,
  [Button.SECONDARY]       : Button.encodeSecondary,
  [Button.SUCCESS]         : Button.encodeSuccess,
  [Button.DANGER]          : Button.encodeDanger,
  [Button.LINK]            : Button.encodeLink,
  [Button.PREMIUM]         : Button.encodePremium,
  [Button.BUTTON]          : Button.encodeButton,
  [Button.ACTIONS]         : Button.encodeActions,
  [Embed.AUTHOR]           : Embed.encodeAuthor,
  [Embed.FIELD]            : Embed.encodeField,
  [Embed.IMAGE]            : Embed.encodeImage,
  [Embed.FOOTER]           : Embed.encodeFooter,
  [Embed.EMBED]            : Embed.encodeEmbed,
  [Container.MESSAGE]      : Container.encodeMessage,
  [Container.EPHEMERAL]    : Container.encodeEphemeral,
  [Container.TEXT_INPUT]   : Container.encodeTextInput,
  [Container.MODAL]        : Container.encodeModal,
  [Select.OPTION]          : Select.encodeOption,
  [Select.SELECT]          : Select.encodeSelect,
  [Select.DEFAULT]         : Select.encodeDefault,
  [Select.CHANNELS]        : Select.encodeChannels,
  [Select.MENTIONS]        : Select.encodeMentions,
  [Select.ROLES]           : Select.encodeRoles,
  [Select.USERS]           : Select.encodeUsers,
};
