name: pr

on:
  pull_request:
    branches: [main]
    paths:    ["*.tf"]
    types:    [synchronize]

concurrency:
  group:              ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name:    validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  echo "todo - terraform CICD credentials"
