name: pr-validate

on:
  pull_request:
    branches: [main]
    paths:    ["terraform/**"]
    types:    [synchronize]

concurrency:
  group:              ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - run: echo "todo - terraform CICD credentials"

