name: PR Verify

on:
  pull_request:
    branches: ['main']
    types: ['synchronize']

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    concurrency: 1

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run types
      - run: pnpm run build
